### ISSUE TITLE
[Feature Request]: Enlarge Secondary Controls

### ISSUE THREAD

**Issue by livejamie** [daksh2k/Spicetify-stuff#185]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

I use a touchscreen device and the secondary controls are hard to touch.

### ➕ Additional Information

It would be nice if there was an option to set their size or make them bigger. Thanks!

**Comment by daksh2k** [comment]
You can use this CSS to make them bigger, adding it configurable from settings won't be possible for now.
```css
#full-screen-display .fs-button {
 transform: scale(1.5);
 margin: 0 5px;
}
#full-screen-display .fs-button:hover {
  transform: scale(1.7);
}
```

<img width="779" alt="image" src="https://github.com/user-attachments/assets/604267ab-7e5f-456f-8fc1-834c6fcdacc4">


See this on how to add styles https://github.com/daksh2k/Spicetify-stuff/issues/157#issuecomment-2090327690
